[api_keys]
newsapi = "635678a6d6ab41dd81af0b8405113f8d"
gemini = "AIzaSyDwm5LduIpWpfqIfsQ4L0rDS_0LnOk4fqw"
deepgram = "4a2c656f35e86daf88ec9b1cc05db4a1efd71edc"
spotify_client_id = "your_spotify_client_id"
spotify_client_secret = "your_spotify_client_secret"